import "./../globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Providers } from "../../provider";
import { AppBar } from "../../components/AppBar"
const kanit = Montserrat({ subsets: ["latin"], weight:["400"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {

  

  return (
    <html lang="en">
      <Providers>
        <body className={`${kanit.className} bg-[#ebe6e6]`}>
          <div className="w-screen flex flex-col h-screen ">
            <div className="h-20 fixed top-0 z-51 w-screen z-50">
              <AppBar/>
            </div>
            <div className="">
              {children}
            </div>
          </div>
        </body>
      </Providers>
    </html>
  );
}


