import "./globals.css";
import type { Metadata } from "next";
import { Caveat, Inter, Montserrat } from "next/font/google";
import { Providers } from "../provider";
import AppBarClient from "../components/AppBarClient";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });
const caveat = Caveat({ subsets: ["latin"] });
const kanit = Montserrat({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <Providers>
        <body className={`${kanit.className} min-h-screen bg-[#020817]`}>
          <div className="bg-[#ebe6e6]">
            <div className="fixed h-20 top-0 z-50">
              {/* <AppBarClient /> */}
            </div>
            <div className="">
              {children}
            </div>
          </div>
        </body>
        <Toaster richColors />
      </Providers>
    </html>
  );
}
